# Generated by Django 5.0.6 on 2024-05-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='id_artikel',
        ),
        migrations.RemoveField(
            model_name='kursus',
            name='harga_kursus',
        ),
        migrations.RemoveField(
            model_name='kursus',
            name='id_kursus',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='id_resep',
        ),
    ]
