# Generated by Django 5.0.6 on 2024-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_artikel_id_remove_kursus_id_remove_resep_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursus',
            name='chef',
            field=models.CharField(default='Sizzle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kursus',
            name='harga_kursus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='kursus',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
