# Generated by Django 5.0.6 on 2024-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_kursus_chef_kursus_harga_kursus_kursus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='harga_kursus',
            field=models.IntegerField(default=0),
        ),
    ]
