# Generated by Django 5.0.6 on 2024-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_kursus_harga_kursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='durasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resep',
            name='porsi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resep',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
