# Generated by Django 5.0.6 on 2024-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resep_durasi_resep_porsi_resep_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='images/resep/'),
        ),
    ]
