# Generated by Django 5.0.6 on 2024-05-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resep_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resep',
            old_name='gambar',
            new_name='gambar_resep',
        ),
        migrations.AddField(
            model_name='kursus',
            name='gambar_kursus',
            field=models.ImageField(blank=True, null=True, upload_to='images/kursus/'),
        ),
    ]
