# Generated by Django 5.0.6 on 2024-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_gambar_resep_gambar_resep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='bahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='cara_membuat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='definisi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='informasi_nutrisi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
