# Generated by Django 5.0.6 on 2024-05-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_kategoriresep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriresep',
            name='nama_resep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='app.resep'),
        ),
    ]
