# Generated by Django 5.0.6 on 2024-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_kategoriresep_nama_resep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoriresep',
            name='nama_resep',
        ),
    ]
