# Generated by Django 5.0.6 on 2024-05-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_kategoriresep_nama_resep'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='kategori_resep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reseps', to='app.kategoriresep'),
        ),
    ]
