# Generated by Django 5.0.6 on 2024-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_resep_kategori_resep'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriresep',
            name='gambar_kategori_resep',
            field=models.ImageField(blank=True, null=True, upload_to='images/resep/'),
        ),
    ]
