# Generated by Django 5.0.6 on 2024-05-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_kategoriresep_gambar_kategori_resep'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKursus',
            fields=[
                ('id_kategori_kursus', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_resep', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='kategoriresep',
            name='gambar_kategori_resep',
        ),
        migrations.AddField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kursuss', to='app.kategorikursus'),
        ),
    ]
