# Generated by Django 5.0.6 on 2024-05-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorikursus',
            old_name='kategori_resep',
            new_name='kategori_kursus',
        ),
    ]
