# Generated by Django 5.0.6 on 2024-05-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_kategori_resep_kategorikursus_kategori_kursus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriKursus',
        ),
    ]
