# Generated by Django 5.0.6 on 2024-05-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_kategorikursus_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriresep',
            name='gambar_kategori_resep',
            field=models.ImageField(blank=True, null=True, upload_to='images/resep/'),
        ),
        migrations.AlterField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='kursuss', to='app.kategorikursus'),
        ),
    ]
