# Generated by Django 5.0.6 on 2024-05-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_kursus_kategori_kursus_delete_kategorikursus'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKursus',
            fields=[
                ('id_kategori_kursus', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_kursus', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='kursuss', to='app.kategoriresep'),
        ),
    ]
