# Generated by Django 5.0.6 on 2024-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriKursus',
        ),
        migrations.AlterField(
            model_name='kursus',
            name='id_kursus',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
