# Generated by Django 5.0.6 on 2024-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorikursus',
            name='id_kategori_kursus',
        ),
        migrations.RemoveField(
            model_name='kursus',
            name='kategori_kursus',
        ),
        migrations.AddField(
            model_name='kategorikursus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
