# Generated by Django 5.0.6 on 2024-05-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_kategorikursus_id_kategori_kursus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriKursus',
        ),
    ]
