# Generated by Django 5.0.6 on 2024-05-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursus',
            name='kategori_kursus',
        ),
        migrations.DeleteModel(
            name='KategoriKursus',
        ),
    ]
