# Generated by Django 5.0.6 on 2024-05-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_kursus_id_kursus'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKursus',
            fields=[
                ('id_kategori_kursus', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_kursus', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kursus',
            name='id_kursus',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.kategorikursus'),
        ),
    ]
