# Generated by Django 5.0.6 on 2024-05-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_kategorikursus_alter_kursus_id_kursus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.kategorikursus'),
        ),
    ]
