# Generated by Django 5.0.6 on 2024-05-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_kursus_id_kursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseps', to='app.kategorikursus'),
        ),
    ]
