# Generated by Django 5.0.6 on 2024-05-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_kursus_kategori_kursus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriKursus',
        ),
    ]
