# Generated by Django 5.0.6 on 2024-05-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_kategorikursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar_artikel',
            field=models.ImageField(blank=True, null=True, upload_to='images/artikel/'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='isi_artikel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori_artikel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='tanggal_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kursus',
            name='kategori_kursus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kursuss', to='app.kategorikursus'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judul_artikel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
