# Generated by Django 5.0.6 on 2024-05-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_artikel_gambar_artikel_artikel_isi_artikel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
