# Generated by Django 5.0.6 on 2024-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_artikel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriTeknik',
            fields=[
                ('id_kategori_teknik', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_teknik', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
