# Generated by Django 5.0.6 on 2024-05-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_kategoriteknik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teknik',
            fields=[
                ('id_teknik', models.AutoField(primary_key=True, serialize=False)),
                ('judul_teknik', models.CharField(max_length=50, unique=True)),
                ('penulis', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('isi_artikel', models.TextField(blank=True, null=True)),
                ('tanggal_upload', models.DateTimeField(blank=True, null=True)),
                ('gambar_artikel', models.ImageField(blank=True, null=True, upload_to='images/teknik/')),
                ('kategori_teknik', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tekniks', to='app.kategoriteknik')),
            ],
        ),
    ]
