# Generated by Django 5.0.6 on 2024-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_teknik'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknik',
            name='tipe_artikel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
