# Generated by Django 5.0.6 on 2024-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_kursus_deskripsi_kursus_kursus_id_kegiatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursus',
            name='deskripsi_singkat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
