# Generated by Django 5.0.6 on 2024-06-07 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_userkursus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkursus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userkursus',
            name='kursus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kursus'),
        ),
        migrations.AlterField(
            model_name='userkursus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userkursus',
            name='tanggal_daftar',
        ),
    ]
