# Generated by Django 5.0.6 on 2024-06-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_kontenkursus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontenkursus',
            name='kursus',
        ),
        migrations.RemoveField(
            model_name='kontenkursus',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='kontenkursus',
            name='tugas',
        ),
        migrations.RemoveField(
            model_name='kontenkursus',
            name='video_url',
        ),
        migrations.AddField(
            model_name='kontenkursus',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/kursus/'),
        ),
        migrations.AddField(
            model_name='kontenkursus',
            name='video',
            field=models.FileField(default=20200504, upload_to='videos/kursus/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kontenkursus',
            name='deskripsi',
            field=models.TextField(default=20200504),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kontenkursus',
            name='judul',
            field=models.CharField(default=20220504, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertemuans', to='app.kursus')),
            ],
        ),
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuis_set', to='app.pertemuan')),
            ],
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.CharField(max_length=50)),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_bahan', to='app.pertemuan')),
            ],
        ),
        migrations.AddField(
            model_name='kontenkursus',
            name='pertemuan',
            field=models.ForeignKey(default=20200504, on_delete=django.db.models.deletion.CASCADE, related_name='konten_kursus', to='app.pertemuan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_set', to='app.pertemuan')),
            ],
        ),
    ]
