# Generated by Django 5.0.6 on 2024-06-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile'),
        ),
    ]
